### ISSUE TITLE
Introduce z-dependent quasar CF

### ISSUE THREAD

**Issue by jmarclegoff** [igmhub/SaclayMocks#41]
Using P. Laurent et al (2017) parametrization of b_qso

z=np.linspace(1.9,3.6,100)
bias=0.278*(1+z)**2 + 0.57
plt.plot(z,bias/5)	# blue
plt.plot(z,bias/(1+z)) # orange
plt.plot(z,bias/(1+z)**1.44) # green
plt.plot(z,bias/(1+z)**1.7)  # red
plt.grid()
![figure_1](https://user-images.githubusercontent.com/28785007/57531813-9e247e80-733a-11e9-948c-88f27ab5d25b.png)
over the z-range [1.9 ; 3.6] bias varies by a factor 2.2.
delta = bias / (1+z) varies less, but still by 1.42, 
so XCF varies by the same 1.42 factor and QSO CF varies by a factor 2.
This is not negligible and should be taken into account.
bias / (1+z)**1.44 varies by 1.14 (XCF analysis assumes bias ~ (1+z)**1.44)
bias / (1+z)**1.7 is constant within the accuracy of the parametrization.

**Comment by jmarclegoff** [comment]
Coles and Jones (1991) show that if g Gaussian(mu,sigma) with xi_g then exp(g) has CF = exp (xi_g) - 1. In order to have a z dependent QSO CF 
**we can draw QSO proportionally to exp[a(z) g] with a(z) = b(z)/(1+z) / [ b_0/(1+z_0) ]**
we have a(z_0)=1 and define xi_QSO(z_0) = b_0^2 xi_m(z_0) = xi_0
so xi_QSO = exp[ a^2 xi ] - 1  and exp [ xi ] - 1 = xi_0
    =>  xi_QSO = exp [ a^2 ln(1+xi_0)] - 1
we plot r * xi_QSO(r) / a^2 for z=2 (blue), z_0=2.33(orange), z=2.6 (green) and z=3.6 (red)
![figure_1](https://user-images.githubusercontent.com/28785007/57690998-57d56500-7643-11e9-87e2-54ec064122c1.png)

if xi_0 << 1 then xi_QSO = a^2 xi_0 and we observe a difference only at small r, i.e. large xi_0(r).
This difference is known so it will be possible to include it in picca_fitter2 model.
@TEtourneau can you implement drawing proportional to exp[a(z) g] , produce one box, 10 catalogues for this box, and check ?

**Comment by londumas** [comment]
@jmarclegoff, thanks for looking into that. In my MgII paper, in figure 7, I found the equation 20, using equation 19. What is nice with equation 19, is that it is the same power-law evolution as for the Lya forest, and thus very simple to implement in picca. But anyway, it does not change much at the end.
```
bquasar(zeff=0.59)=1.24±0.05
γquasar=1.44±0.08
Corr=−93%
```

**Comment by jmarclegoff** [comment]
@londumas, here is a plot of Laurent et al. parameterisation of b_QSO(z) (blue) , the parameterisation in your MG ii paper (orange) and b = 3.7 * ((1+z)/(1+2.33)**1.7 (green)
![figure_1](https://user-images.githubusercontent.com/28785007/57760275-84e54e80-76fb-11e9-85c8-43c87d2b1c97.png)
We see that the parameterisation in MG ii paper, designed for low z, is not very good for lya,
whereas the green curves is very closed to the blue one in the range [1.3 , 3.6] covered by our boxes. It agrees within 1% for z>1.6 and within 3% for z>1.3.
So we can use b = 3.7 * ((1+z)/(1+2.33)**1.7 instead of 0.278*(1+z)**2 + 0.57 is this is more convenient in picca. Is that ok ?
If my plot is correct I would also suggest to assume b ~ (1+z)**1.7 in the XCF analysis instead of (1+z)**1.44.

**Comment by londumas** [comment]
I have no preference for the mocks between orange and green, however I think it is way better than blue. So ok if you want to use `b = 3.7 * ((1+z)/(1+2.33)**1.7`. Thanks @jmarclegoff.

**Comment by TEtourneau** [comment]
Just to let you know, currently in the mocks we are using:
b = 3.7 at z=2.4, not z=2.33.
Here are the differences: 
![Screen Shot 2019-05-16 at 8 34 58 AM](https://user-images.githubusercontent.com/36950825/57831549-bde1f980-77b5-11e9-92d3-a8ed474498ac.png)

blue: bias1 = 3.7 * ((1+z)/(1+2.33))**1.7
orange: bias2 = 3.7 * ((1+z)/(1+2.4))**1.7
green: bias3 = 0.278*(1+z)**2 + 0.57

Differences are small, but since the QSO correlation was really good, maybe we should aim to the orange curve.
I'll plot the QSO correlation as soon as I get it.

**Comment by TEtourneau** [comment]
Here is a plot showing the 3 wedges for a QSO-QSO correlation function with a(z) = 1.5 in P ~ exp(a(z) delta)
![image](https://user-images.githubusercontent.com/36950825/59256105-868b2f00-8c33-11e9-9cdd-954e567fa43e.png)

The correlation at small r is looking bad because we don't have: Xi << 1 and a(z) is far from 1.

**Comment by jmarclegoff** [comment]
To improve the procedure, we can produce two lognormal boxes corresponding to z_1 = 2.1 and z_2 = 3.5. We compute P1 = exp[a(z) g_1] with a(z) = b(z)/(1+z) / [ b_0/(1+z_1) ] and similarly P2 for z_2. 
In a voxel at z we draw QSO proportional to a linear interpolation or extrapolation between P1 and P2.  This gives much closer values of r * xi(r) / a^2 as can be seen below.
z= 1.9 (blue), 2.1 or 3.5 (orange), 2.6 (green), 2.9 (purple), 3.6 (red).
![image](https://user-images.githubusercontent.com/28785007/60081762-b4dc3480-9732-11e9-967f-9d3175d1b729.png)
 zoom:
![image](https://user-images.githubusercontent.com/28785007/60081775-bdcd0600-9732-11e9-9c89-abde8e376a05.png)

**Comment by jmarclegoff** [comment]
When we do an interpolation (z_1 < z < z_2) the resulting xi(r) is too large at small r, while it is too low  for an extrapolation (z < z_1 or z > z_2). If we now produce three lognormal boxes at z_1=1.9, z_2=2.75 and z_3=3.6 and consider e.g. z=2.3, the plot below shows the ratio r1 = xi /a^2(z) / xi_0 obtained by interpolating over [1.9;2.75] in blue and r2 obtained by extrapolating from [2.75;3.6] in orange. The two shapes are opposite and similar, so we can combine them to get a significant improvement. We compute the coefficient c such that r12 = c r_1 + (1-c) r_2 is exactly unity at r = 5 mpc/h. For z = 2.3 this gives c = 0.625 and the green curve, which remains within 0.1% of unity for r > 2 Mpc/h (see zoom below).
This done by code xiQSO.py, which also tells us that for r > 5 we always have  0.9997 < r12 < 1.00035 and 0.988 < r12 < 1.0064 for r = 0.



![image](https://user-images.githubusercontent.com/28785007/60083213-97f53080-9735-11e9-8985-297cd9237a79.png)

![image](https://user-images.githubusercontent.com/28785007/60085551-cc6aeb80-9739-11e9-94d6-1bf0379850d5.png)

**Comment by TEtourneau** [comment]
Since version v4.6, the mocks include 3 lognormal fields that are interpolated in order to compute xi_qso at any redshift. The 3 lognormal boxes are produced at z1 = 1.9, z2 = 2.75, z3 = 3.6.
Here are plots showing the auto-correlation of QSO in 3 redshift bins:
- 1.8 < z < 2.1
![image](https://user-images.githubusercontent.com/36950825/65602582-68f49200-dfa4-11e9-93ba-8ab9c0920bcb.png)
![image](https://user-images.githubusercontent.com/36950825/65602600-6db94600-dfa4-11e9-9f61-3b4ac9d59e69.png)

- 2.1 < z < 2.5
![image](https://user-images.githubusercontent.com/36950825/65602637-7e69bc00-dfa4-11e9-9394-4bb2e018b7f5.png)
![image](https://user-images.githubusercontent.com/36950825/65602639-80337f80-dfa4-11e9-8b9b-f61a583dd382.png)

- 2.5 < z < 3.6
![image](https://user-images.githubusercontent.com/36950825/65602691-9b9e8a80-dfa4-11e9-8bc0-b5f7a958f07f.png)
![image](https://user-images.githubusercontent.com/36950825/65602697-9d684e00-dfa4-11e9-9725-711d7b0d35ed.png)


And here is the fitted beta and growth rate, as well as the measured bias compared to the input bias:
![image](https://user-images.githubusercontent.com/36950825/65602747-b2dd7800-dfa4-11e9-95cf-d7d0f3e51b7c.png)
![image](https://user-images.githubusercontent.com/36950825/65602750-b4a73b80-dfa4-11e9-9e2d-7587ca72497e.png)
![image](https://user-images.githubusercontent.com/36950825/65602757-b670ff00-dfa4-11e9-9c28-fc8bd71e521e.png)

**Comment by londumas** [comment]
@TEtourneau, looks very good. Congrats
